### ISSUE TITLE
How to complie or run the GridWorld.ipynb in fold 3D_path_finding?

### ISSUE THREAD

**Issue by ConnLiu** [AirSimDroneSimulator/AirSim#3]
When I run the test.py, there will be two problems:
1、when run it in Spyder, the error is: (Finally, I matually delete the DDPG.  then it becaome " from Actor import Actor", then this problem was solved, **but I wonder if there is a better solution without changing the codes?** )

  File "D:/Projects/codes/AirSim-Object Tracing/3D_path_finding/DDPG/main.py", line 4, in <module>
    from DDPG import DDPG_agent

  File "D:\Projects\codes\AirSim-Object Tracing\3D_path_finding\DDPG\DDPG.py", line 4, in <module>
    from DDPG.Actor import Actor

ModuleNotFoundError: No module named 'DDPG.Actor'; 'DDPG' is not a package

2、after solved problem 1,  next problem came like this( solutions is https://github.com/AirSimDroneSimulator/AirSim/issues/2, but where can I find updateapi.md??  )

Waiting for connection: Traceback (most recent call last):
  File "D:/Projects/codes/AirSim-Object Tracing/3D_path_finding/DDPG/test.py", line 58, in <module>
    main()
  File "D:/Projects/codes/AirSim-Object Tracing/3D_path_finding/DDPG/test.py", line 20, in main
    env = drone_env_heightcontrol()
  File "D:\Projects\codes\AirSim-Object Tracing\3D_path_finding\DDPG\drone_env.py", line 135, in __init__
    drone_env.__init__(self,start,aim)
  File "D:\Projects\codes\AirSim-Object Tracing\3D_path_finding\DDPG\drone_env.py", line 17, in __init__
    self.client.confirmConnection()
  File "D:\Projects\codes\AirSim-Object Tracing\3D_path_finding\DDPG\AirSimClient.py", line 210, in confirmConnection
    home = self.getHomeGeoPoint()
  File "D:\Projects\codes\AirSim-Object Tracing\3D_path_finding\DDPG\AirSimClient.py", line 219, in getHomeGeoPoint
    return GeoPoint.from_msgpack(self.client.call('getHomeGeoPoint'))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python36\site-packages\msgpackrpc\session.py", line 41, in call
    return self.send_request(method, args).get()
  File "C:\Users\lenovo\AppData\Roaming\Python\Python36\site-packages\msgpackrpc\future.py", line 45, in get
    raise error.RPCError(self._error)
msgpackrpc.error.RPCError: rpclib: client error C0002: Function 'getHomeGeoPoint' was called with an invalid number of arguments. Expected: 0, got: 1

**Comment by zhangrh93** [comment]
Please use the notebook in [3D_path_finding](../tree/master/3D_path_finding):
 [GridWorld.ipynb](../tree/master/3D_path_finding/GridWorld.ipynb),
 [HeightControl.ipynb](../tree/master/3D_path_finding/HeightControl.ipynb) and
 [ImgConrtol.ipynb](../tree/master/3D_path_finding/ImgConrtol.ipynb).
These are codes used to start your training for all three tasks.

**Comment by ConnLiu** [comment]
> Please use the notebook in [3D_path_finding](../tree/master/3D_path_finding):
> [GridWorld.ipynb](../tree/master/3D_path_finding/GridWorld.ipynb),
> [HeightControl.ipynb](../tree/master/3D_path_finding/HeightControl.ipynb) and
> [ImgConrtol.ipynb](../tree/master/3D_path_finding/ImgConrtol.ipynb).
> These are codes used to start your training for all three tasks.

Forget to mention that I have run the GridWorld.ipynb, but still meet error like that “getHomeGeoPoint”(which I-have mention before)
And I have search and found this sentence “ I later find it is the version, this project is based on AirSim older version while I am on v1.2.0, refer to update api .md file for solutions”, so I wonder how to fix it?

PS: your codes were really excellent. So I will be very grateful if **you would like to tell me how you write these codes**. I am student and I am trying to write some projects by AirSim .

**Comment by Niann** [comment]
Hi,  

After digging some source code, I find that most of the code in [AirSimClient.py](https://github.com/AirSimDroneSimulator/AirSim/blob/master/3D_path_finding/DDPG/AirSimClient.py) has changed in the [lastest version](https://github.com/Microsoft/AirSim/blob/master/PythonClient/airsim/client.py) (and also the name). The function **getHomeGeoPoint** in lastest version has 0 argument while in older version it has 1, which is also suggested by the trace tree. I doubt there would be more issues rising up even after you fix this one.  

To fix the problem, you can  
1. change the code in client.py in lastest version 
2. use helper functions to wrap those incompatiable functions.
3. simply change the code where problem rises up

Finally, if you really want to write projects in AirSim, I strongly recommand you to read source code to figure out those API cuz the documentation sucks. Good luck!

**Comment by ConnLiu** [comment]
Hi,
Your suggestions are really helpful, thanks very much! 
I will dig the source codes.
