### ISSUE TITLE
Why use both state X and image as input to the network at the same time？

### ISSUE THREAD

**Issue by Curry30h** [AirSimDroneSimulator/AirSim#4]

**Comment by Niann** [comment]
Hi,

Because in our environment the state space consists of physical state like position and speed as well as image get from camera. If we remove the state X, then the problem needs to be modeled as a POMDP problem and use a RNN to keep track of history. Speed info can also be indirectly infered by stacking frames like how DQN solves Atari games. You can try any of these if you are interested.

**Comment by Curry30h** [comment]
Thank you very much for your reply, I am really happy to hear from you，even grateful.Then the variable X represents the value of its own speed and position? I see that the dimension of this variable in your code is 1, is it passed to the network in the form of [pos, vel]? I wonder if this is the case when training an unmanned vehicle. Also when I run your code with the getState() function in the env script, state = [img, np.array([pos[2] - self.aim_height])] will generate an error: too many indices for array. I seem to have changed the size of the input image before. In addition, in the Actor network, I don't understand the function of the _seperate_image() function and the method of implementing the function. I hope you can teach me. thank you very much.




------------------ 原始邮件 ------------------
发件人: "Niann"<notifications@github.com>;
发送时间: 2019年4月22日(星期一) 中午12:46
收件人: "AirSimDroneSimulator/AirSim"<AirSim@noreply.github.com>;
抄送: "421090349"<421090349@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [AirSimDroneSimulator/AirSim] Why use both state X and image as input to the network at the same time？ (#4)




Hi,
 
Because in our environment the state space consists of physical state like position and speed as well as image get from camera. If we remove the state X, then the problem needs to be modeled as a POMDP problem and use a RNN to keep track of history. Speed info can also be indirectly infered by stacking frames like how DQN solves Atari games. You can try any of these if you are interested.
